[project]
name = "udi-hunterdouglas-pg3x"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "udi-interface",
    "requests",
    "aiohttp",
]

[dependency-groups]
dev = [
    "pre-commit",
    "pytest",
    "pytest-cov",
]
lint = [
    "ruff",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
